### ISSUE TITLE
Test Accuracy Compared to Paper using my own trained model

### ISSUE THREAD

**Issue by zhhezhhe** [facebookresearch/DensePose#162]
I see the https://github.com/facebookresearch/DensePose/issues/126 .But when I train the model using DensePose_ResNet50_FPN_s1x-e2e.yaml, I got INFO task_evaluation.py: 200: copypaste: 0.4748,0.8447,0.4892,0.4017,0.4928 which is different from 0.4892,0.8490,0.5078,0.4384,0.5059 (using https://s3.amazonaws.com/densepose/DensePose_ResNet50_FPN_s1x-e2e.pkl).

**Comment by zhhezhhe** [comment]
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  BODY_UV_ON: True
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  GAMMA: 0.1
  WARM_UP_ITERS: 1000
  WARM_UP_FACTOR: 0.1
  # Linear scaling rule:
  # 1 GPU:
  #   BASE_LR: 0.00025
  #   MAX_ITER: 720000
  #   STEPS: [0, 480000, 640000]
  # 2 GPUs:
  #   BASE_LR: 0.0005
  #   MAX_ITER: 360000
  #   STEPS: [0, 240000, 320000]
  # 4 GPUs:
  #  BASE_LR: 0.001
  #  MAX_ITER: 180000
  #  STEPS: [0, 120000, 160000]
  #8 GPUs:
  BASE_LR: 0.001
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
BODY_UV_RCNN:
  ROI_HEAD: body_uv_rcnn_heads.add_roi_body_uv_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_PATCHES: 24
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  ##
  # Loss weights for annotation masks.(14 Parts)
  INDEX_WEIGHTS : 2.0
  # Loss weights for surface parts. (24 Parts)
  PART_WEIGHTS : 0.3
  # Loss weights for UV regression.
  POINT_REGRESSION_WEIGHTS : 0.1
  ##
  BODY_UV_IMS: True
TRAIN:
  WEIGHTS: /home/vis/zhenghe/DensePose-master/pkls/R-50.pkl
  DATASETS: ('dense_coco_2014_train', 'dense_coco_2014_valminusminival')
  SCALES: (640, 672, 704, 736, 768, 800)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 3
  BATCH_SIZE_PER_IM: 512
  USE_FLIPPED: True
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('dense_coco_2014_minival',)
  PROPOSAL_LIMIT: 1000
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  FORCE_JSON_DATASET_EVAL: True
  DETECTIONS_PER_IM: 20
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: ''

**Comment by zhhezhhe** [comment]
```
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  BODY_UV_ON: True
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  GAMMA: 0.1
  WARM_UP_ITERS: 1000
  WARM_UP_FACTOR: 0.1
  # Linear scaling rule:
  # 1 GPU:
  #   BASE_LR: 0.00025
  #   MAX_ITER: 720000
  #   STEPS: [0, 480000, 640000]
  # 2 GPUs:
  #   BASE_LR: 0.0005
  #   MAX_ITER: 360000
  #   STEPS: [0, 240000, 320000]
  # 4 GPUs:
  #  BASE_LR: 0.001
  #  MAX_ITER: 180000
  #  STEPS: [0, 120000, 160000]
  #8 GPUs:
  BASE_LR: 0.001
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
BODY_UV_RCNN:
  ROI_HEAD: body_uv_rcnn_heads.add_roi_body_uv_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_PATCHES: 24
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 56
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  ##
  # Loss weights for annotation masks.(14 Parts)
  INDEX_WEIGHTS : 2.0
  # Loss weights for surface parts. (24 Parts)
  PART_WEIGHTS : 0.3
  # Loss weights for UV regression.
  POINT_REGRESSION_WEIGHTS : 0.1
  ##
  BODY_UV_IMS: True
TRAIN:
  WEIGHTS: /home/vis/zhenghe/DensePose-master/pkls/R-50.pkl
  DATASETS: ('dense_coco_2014_train', 'dense_coco_2014_valminusminival')
  SCALES: (640, 672, 704, 736, 768, 800)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 3
  BATCH_SIZE_PER_IM: 512
  USE_FLIPPED: True
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('dense_coco_2014_minival',)
  PROPOSAL_LIMIT: 1000
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  FORCE_JSON_DATASET_EVAL: True
  DETECTIONS_PER_IM: 20
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: ''
```
